In [1]:
my_dict = {
    "key1": 1,
    "key2": 2
}

In [2]:
my_dict

{'key1': 1, 'key2': 2}

In [3]:
type(my_dict)

dict

In [4]:
type(1000)

int

In [5]:
type("Hello world!")

str

In [6]:
1000 + "Hello world!"

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [7]:
 "Hello" + "world!"

'Helloworld!'

In [8]:
my_list = [1, 2, 5, 6, 7, 8, 9, 1000]

In [9]:
len(my_list)

8

In [11]:
my_list[-1]

1000

In [12]:
my_list[-2]

9

In [13]:
type(my_list)

list

In [14]:
type(my_list[0])

int

In [15]:
my_other_list = [5, 3, 1, 65, 8, 23, 6]

In [16]:
sorted(my_other_list)

[1, 3, 5, 6, 8, 23, 65]

In [17]:
my_other_list.append(100000)

In [18]:
my_other_list

[5, 3, 1, 65, 8, 23, 6, 100000]

In [19]:
my_other_list.sort()

In [20]:
my_other_list

[1, 3, 5, 6, 8, 23, 65, 100000]

In [23]:
my_list + my_other_list

[1, 2, 5, 6, 7, 8, 9, 1000, 1, 3, 5, 6, 8, 23, 65, 100000]

In [24]:
my_list.extend(my_other_list)

In [25]:
my_list

[1, 2, 5, 6, 7, 8, 9, 1000, 1, 3, 5, 6, 8, 23, 65, 100000]

In [26]:
my_other_list

[1, 3, 5, 6, 8, 23, 65, 100000]

In [27]:
breakfast = {
    "eggs": 1,
    "bacon": 2,
    "sausage": 10
}
breakfast

{'eggs': 1, 'bacon': 2, 'sausage': 10}

In [28]:
breakfast["sausage"] = 5
breakfast

{'eggs': 1, 'bacon': 2, 'sausage': 5}

In [29]:
breakfast["sausage"] = "No thanks, I don't like sausages!"

In [30]:
breakfast

{'eggs': 1, 'bacon': 2, 'sausage': "No thanks, I don't like sausages!"}

In [31]:
breakfast.keys()

dict_keys(['eggs', 'bacon', 'sausage'])

In [32]:
breakfast.values()

dict_values([1, 2, "No thanks, I don't like sausages!"])

In [33]:
import numpy as np
import pandas as pd

In [34]:
a = [1, 2, 3, 4, 5, 6]
b = [20, 30, 40, 50, 60, 70]
a + b

[1, 2, 3, 4, 5, 6, 20, 30, 40, 50, 60, 70]

In [35]:
a - b

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [36]:
a * b

TypeError: can't multiply sequence by non-int of type 'list'

In [37]:
A = np.array([1, 2, 3, 4, 5, 6])
B = np.array([20, 30, 40, 50, 60, 70])

In [40]:
C = A + B
C

array([21, 32, 43, 54, 65, 76])

In [41]:
A - B

array([-19, -28, -37, -46, -55, -64])

In [42]:
A * B

array([ 20,  60, 120, 200, 300, 420])

In [43]:
A + np.array([2, 3])

ValueError: operands could not be broadcast together with shapes (6,) (2,) 

In [44]:
C

array([21, 32, 43, 54, 65, 76])

In [48]:
C[6]

IndexError: index 6 is out of bounds for axis 0 with size 6

In [49]:
C[:4]

array([21, 32, 43, 54])

In [50]:
features = {
    "animals": ["python", "lynx", "giant panda", "field mouse", "octopus"],
    "limb": [0, 4, 4, 4, 8],
    "herbivore": [False, False, True, True]
}

In [51]:
df = pd.DataFrame(features, index=features['animals'])
df

animals  limb  herbivore
python            python     0      False
lynx                lynx     4      False
giant panda  giant panda     4       True
field mouse  field mouse     4       True
octopus          octopus     8      False

In [52]:
df.head(3)

animals  limb  herbivore
python            python     0      False
lynx                lynx     4      False
giant panda  giant panda     4       True

In [53]:
df.sample(2)

animals  limb  herbivore
field mouse  field mouse     4       True
giant panda  giant panda     4       True

In [55]:
df.sample(2)

animals  limb  herbivore
field mouse  field mouse     4       True
python            python     0      False

In [57]:
pd.DataFrame({
    "animals": ["python", "lynx", "giant panda", "field mouse", "octopus"],
    "limb": [0, 4, 4, 4, 8],
    "herbivore": [False, False, True, True]
})

ValueError: arrays must all be same length

In [62]:
df["limb"]

python         0
lynx           4
giant panda    4
field mouse    4
octopus        8
Name: limb, dtype: int64

In [64]:
df.herbivore

python         False
lynx           False
giant panda     True
field mouse     True
octopus        False
Name: herbivore, dtype: bool

In [73]:
df.limb

python         0
lynx           4
giant panda    4
field mouse    4
octopus        8
Name: limb, dtype: int64

In [71]:
np.array(df.limb)

array([0, 4, 4, 4, 8])

In [82]:
df

animals  limb  herbivore
python            python     0      False
lynx                lynx     4      False
giant panda  giant panda     4       True
field mouse  field mouse     4       True
octopus          octopus     8      False

In [81]:
df.describe()

limb
count  5.000000
mean   4.000000
std    2.828427
min    0.000000
25%    4.000000
50%    4.000000
75%    4.000000
max    8.000000

In [83]:
df.herbivore.describe()

count         5
unique        2
top       False
freq          3
Name: herbivore, dtype: object

In [85]:
df.limb.sum()

20

In [86]:
df.animals.sum()

'pythonlynxgiant pandafield mouseoctopus'

In [87]:
df.animals.count()

5

In [88]:
df.animals.value_counts()

giant panda    1
lynx           1
field mouse    1
octopus        1
python         1
Name: animals, dtype: int64

In [89]:
df.herbivore.value_counts()

False    3
True     2
Name: herbivore, dtype: int64

In [91]:
df.limb.value_counts()

4    3
8    1
0    1
Name: limb, dtype: int64